### ISSUE TITLE
systolic_array project

### ISSUE THREAD

**Issue by rhysaeron** [Xilinx/SDSoC_Examples#2]
I ran the Systolic Array project on the ZCU102, and the software seems to have a 5th of the number of CPU cycles than the hardware, yet the whole point of the Systolic Array is that it is more ideal for an FPGA than matrices. Could you explain why this is??

**Comment by heeran-xilinx** [comment]
Hi @rhysaeron ,
Thanks for reporting this issue. We are looking into  this. 

-Heera

**Comment by heeran-xilinx** [comment]
Closing this issue as this repository is only for older released version of tool and no more support is available.
Please use latest Repository: https://github.com/Xilinx/Vitis_Accel_Examples for Xilinx latest Tool chain.
