### ISSUE TITLE
ap_uint<1> and access randomly

### ISSUE THREAD

**Issue by tangjie77wd** [Xilinx/SDSoC_Examples#3]
I have a project similar to Xilinx/SDSoC_Examples/cpp/getting_started/data_access_random/src/ which means I want to access arrays randomly.Here is my some code below:
`#pragma SDS data copy(stonesimg[0:HEIGHT*WIDTH],valve_column_[0:64],valvearray[0:HEIGHT*64])
#pragma SDS data access_pattern(stonesimg:RANDOM,valve_column_:RANDOM,valvearray:RANDOM)
#pragma SDS data data_mover(stonesimg:AXIDMA_SIMPLE,valve_column_:AXIDMA_SIMPLE,valvearray:AXIDMA_SIMPLE)
void convertvalve(ap_uint<1> stonesimg[HEIGHT*WIDTH],ap_uint<10> valve_column_[64],ap_uint<1> valvearray[HEIGHT*64]);`
But the following error appears when i try to build it:
`Creating block diagram (BD)
Creating top.bd.tcl
ERROR: [CF2XD 83-22322] BRAM data width (1-bits) for port 'stonesimg_V_PORTA' must be a multiple of 8.  
ERROR: [CF2XD 83-22322] You can use a Vivado HLS interface pragma to map to an AXI4 stream interface.
ERROR: [CF2XD 83-2239] failed to create xd_adapter for accelerator comp convertvalve_1
ERROR: [CF2XD 83-2009] An error has occurred during generation of the system block diagram.  For more information, please look for additional ERROR messages in the console and in log files.
Error generating intermediate design file top.xml
Error creating IPI .bd design file, exiting`
This seems randomly access and 1 bit BRAM data width which i want to apply at the same time are mutually exclusive?! I know the error information will disappear if i change access_pattern to SEQUENTIAL from RANDOM ! But i really need randomly access.

**Comment by heeran-xilinx** [comment]
Hi @tangjie77wd ,
Could you please post SDSoC related queries to Xilinx Forum?
https://forums.xilinx.com/t5/SDSoC-Environment-and-reVISION/bd-p/sdsoc

-Heera

**Comment by heeran-xilinx** [comment]
Closing this issue as this repository is only for older released version of tool and no more support is available.
Please use latest Repository: https://github.com/Xilinx/Vitis_Accel_Examples for Xilinx latest Tool chain.
